docs/guide/migration.md
docs/zh/guide/migration.md

Following https://github.com/vuepress/vuepress-next/issues/112

docs: add plugin link in migration guide

---

packages/@vuepress/theme-default/src/client/styles/code.scss

Closes #124 by removing `'Courier New'` as font which caused the issue.
Must I adjust https://github.com/vuepress/vuepress-next/blob/e971d6aa216102befaa387e062d49b3632fe579c/packages/%40vuepress/theme-default/src/client/styles/_normalize.scss#L114 as well?
Not quite sure if the fix is in `core`, maybe adjust the commit message when merging.

fix(theme-default): align the font of line numbers with code blocks (close #124)

---

docs/guide/getting-started.md
docs/zh/guide/getting-started.md

When executing `echo 'node_modules\n.temp\n.cache' >> .gitignore` in PowerShell on Windows, pwsh appends a single line `node_modules\n.temp\n.cache` to .gitignore file. Change it to adding each line respectively so that it can work in PowerShell.

docs: make guide for .gitignore work on Windows

---

packages/@vuepress/markdown/__tests__/plugins/assetsPlugin.spec.ts
packages/@vuepress/markdown/package.json
packages/@vuepress/markdown/src/plugins/assetsPlugin.ts

This is an issue in all VuePress versions.
```md
```
should be allowed. But `markdown-it` 's default behavior will encode it to `./%E4%B8%AD%E5%9B%BD.png`, so that  bundler won't be able to find the image file.
I made a fix in V1 by my `vuepress-plugin-md-enhance`, but I think V2 can support it.

fix(markdown): decode assets link to ensure bundler can find the file

---

packages/@vuepress/client/package.json
packages/@vuepress/plugin-docsearch/package.json
packages/@vuepress/plugin-pwa-popup/package.json
packages/@vuepress/plugin-search/package.json
packages/@vuepress/plugin-theme-data/package.json
packages/@vuepress/plugin-toc/package.json
packages/@vuepress/theme-vue/package.json
packages/@vuepress/theme-vue/tsconfig.build.json

1. some package used in source code, but not listed in `package.json`
| repo dir  | missing deps | used in |
| -- | -- | -- |
| @vuepress/client | vite | https://github.com/vuepress/vuepress-next/blob/e028f887ee9ee10d52abff9e37a9148139372e43/packages/%40vuepress/client/tsconfig.json#L22 |
| @vuepress/plugin-docsearch | @docsearch/react | https://github.com/vuepress/vuepress-next/blob/e028f887ee9ee10d52abff9e37a9148139372e43/packages/%40vuepress/plugin-docsearch/src/shared/types.ts#L1 |
| @vuepress/plugin-pwa-popup | vue | https://github.com/vuepress/vuepress-next/blob/e028f887ee9ee10d52abff9e37a9148139372e43/packages/%40vuepress/plugin-pwa-popup/src/client/components/PwaPopup.ts#L1 |
| @vuepress/plugin-search | vite | https://github.com/vuepress/vuepress-next/blob/e028f887ee9ee10d52abff9e3 …

build: add missing deps

---

packages/@vuepress/plugin-search/src/client/components/SearchBox.ts

By default form element on Enter key press would try to send form request to current page, essentially reloading the page.

fix(plugin-search): disable default form action on Enter key

---

packages/@vuepress/shared/tsconfig.esm.json

By default with our config, typescript will generate a `.tsbuildinfo` file in the parent directory of the `outDir`. However, the parent of `./lib/esm` is `./lib` which is the publish dir, we have to explicitly specify path of `.tsbuildinfo`.
This will avoid publish `.tsbuildinfo` file, which has a size of 32kb, the `lib` folder will shrink from 65.1kb to 32.0kb.

build(shared): avoid publishing tsbuildinfo

---

packages/@vuepress/theme-default/src/client/components/Navbar.vue
packages/@vuepress/theme-default/src/client/styles/dropdown.scss

The default theme contains certain styles and logic that execute at a media query breakpoint of 719px screen width. However, there is some overlap of styling and behavior of the nav bar / sidebar at exactly 719px (i.e., behavior is as expected at 718px and 720px, but not 719px). These commits alleviate those issues.

fix(theme-default): fix nav glitch at exactly 719px screen width

---

docs/reference/plugin/active-header-links.md
docs/zh/reference/plugin/active-header-links.md
packages/@vuepress/plugin-active-header-links/src/node/activeHeaderLinksPlugin.ts
packages/@vuepress/theme-default/src/node/utils/resolveActiveHeaderLinksPluginOptions.ts

Since the SidebarChild's template got updated from `.sidebar-link` to `.sidebar-item` in ea7c4bb, the default value for `headerLinkSelector` on the active-header-links plugin doesn't exist anymore (at least not on the default theme).

fix(plugin-active-header-links): update active header link selector

---

packages/@vuepress/theme-default/src/client/styles/normalize.scss

See https://github.com/vuepress/vuepress-next/issues/266

fix(theme-default): break long links on overflow (close #266)

---

packages/@vuepress/theme-default/src/shared/options.ts

The `docsBranch` option now defaults to `'main'`, not `'master'`

chore(theme-default): update docsBranch description

---

packages/@vuepress/theme-default/src/client/components/ToggleDarkModeButton.vue
packages/@vuepress/theme-default/src/client/composables/index.ts
packages/@vuepress/theme-default/src/client/composables/useDarkMode.ts
packages/@vuepress/theme-default/src/client/composables/useHTMLClass.ts
packages/@vuepress/theme-default/src/client/composables/useHtmlDarkClass.ts
packages/@vuepress/theme-default/src/client/composables/usePrefersColorScheme.ts

This PR uses a global ref to make sure `useDarkMode()` still be of actual use in inherited theme development.

fix(theme-default): use a global isDarkMode ref

---

docs/advanced/cookbook/extending-a-theme.md
docs/zh/advanced/cookbook/extending-a-theme.md

I'm sorry for my carelessness.
> But I remember my configuration pasted from the document and it used to seem like 'extend'. I thought it might appear in changelog, but I didn't find it.
Perhaps typescript type tip is a better idea to use them as examples in a document.

docs: add ts demo for extending-a-theme

---

packages/@vuepress/theme-default/src/client/styles/navbar.scss

Currently the `min-width` css property stretches non-square logos. I'm not exactly sure if there are any cases where it is beneficial.
Before:
After:

fix(theme-default): improve the style for non-square logo

---

packages/@vuepress/plugin-git/src/node/utils/getContributors.ts

Close #205
Git shortlog produces empty output in cases when HEAD is detached.
From git shortlog [docs](https://git-scm.com/docs/git-shortlog):
`
If no revisions are passed on the command line and either standard input is not a terminal or there is no current branch, git shortlog will output a summary of the log read from standard input, without reference to the current repository.
`
This PR add HEAD into shortlog arguments as revision.
Use case: At gitlab-ci job log:
```
Fetching changes...
Reinitialized existing Git repository in #doesnt_matter#
Checking out 0aac9a9b as master...
...
git status
HEAD detached at 0aac9a9
Untracked files:
(use "git add <file>..." to include in what will be committed)
package.json
nothing added to commit but untracked files present (use "git add" to track) …
```

fix(plugin-git): add HEAD into git shortlog arguments (close #205)

---

packages/@vuepress/theme-default/src/client/styles/home.scss

This PR fixes #381 
_This uses `gap` in flexbox. I don't know what the browser support requirements for vuepress-next are, but `gap` is supported in all major browsers (see [here](https://caniuse.com/flexbox-gap))_

fix(theme-default): hero actions spacing on small devices (close #381)

---

packages/@vuepress/theme-default/src/client/styles/normalize.scss

fix kbd color in dark mode
if the type is warning in Custom Containers, the kbd text hard to read
the fixed color of kbd will be better
before:
after:

fix(theme-default): fix kbd color in dark mode

---

packages/@vuepress/theme-default/src/client/components/PageMeta.vue

Improve the "Last Updated" date by no longer using the language of the page to generate the date, but letting the browser choose the correct format according to the operating system/browser settings.
_This has emerged from a discussion in #431, although it does not "fix" the actual feature request._

fix(theme-default): use browser default locale in last updated date

---

packages/@vuepress/theme-default/package.json
yarn.lock

PR bumps @vueuse/core from 7.1.2 to 7.5.3 and fixes problem with blank page in #589 
Affected entities:
@vueuse is only used in useDarkMode
- usePreferredDark did not change since 7.1.2
- useStorage implemented [fix for DOMException](https://github.com/vueuse/vueuse/commit/77fe0fbc3f1b3b1cae8b23bb7f1d1fc3c0fd0922)
Update should not cause any problems

fix(theme-default): bump vueuse to avoid localstorage error (close #589)

---

packages/@vuepress/theme-default/src/client/styles/custom-container.scss

fixed #648 
When there's no content in custom container, the title of custom container is not centered up and down, and the reason is that `margin-bottom: -0.4em;` overwrites the original `margin-bottom` of the `p` tag. So removing this style ensures that the title is center when no content in custom container. In addition, the container is not affected when it has content.
style of container without content:
style of container with content:

feat(theme-default): fix title style when no content in custom container (close #648)

---

docs/guide/migration.md
docs/zh/guide/migration.md

@Mister-Hope recommended adding docs about themeConfig access to the v2 migration guide after he answered [this question](https://github.com/vuepress/vuepress-next/discussions/686)

docs: add migration guide for theme data

---

packages/@vuepress/theme-default/src/client/components/Navbar.vue
packages/@vuepress/theme-default/src/client/components/NavbarDropdown.vue
packages/@vuepress/theme-default/src/client/components/NavbarItems.vue
packages/@vuepress/theme-default/src/client/styles/navbar-dropdown.scss

This pull request introduces different transition behaviors for header and aside navbars:
- header: transform & opacity, just like https://vuejs.org
- aside: collapse (DropdownTransition)

feat(theme-default): enhance header dropdown experience

---

docs/reference/default-theme/frontmatter.md
docs/reference/plugin/git.md
docs/zh/reference/default-theme/frontmatter.md
docs/zh/reference/plugin/git.md
packages/@vuepress/plugin-git/package.json
packages/@vuepress/plugin-git/src/node/gitPlugin.ts
packages/@vuepress/plugin-git/src/node/types.ts
packages/@vuepress/plugin-git/src/node/utils/getContributors.ts
packages/@vuepress/plugin-git/src/node/utils/getCreatedTime.ts
packages/@vuepress/plugin-git/src/node/utils/getUpdatedTime.ts
packages/@vuepress/plugin-git/tsconfig.build.json
pnpm-lock.yaml

close #449
This PR allows users to provide a per page frontmatter field `gitInclude` of type `string[]`.
This field is an array of relative file paths to be included in calculating git attributes `git.createdTime`, `git.updatedTime`, and `git.contributors`
Please check this [PR](https://github.com/LucienZhang/vuepress-next/pull/2) for the test details.

feat(plugin-git): take additional files in calculating git attributes (close #449)

---

packages/@vuepress/plugin-active-header-links/src/client/composables/useActiveHeaderLinks.ts

Linked with this feature request issue https://github.com/vuepress/vuepress-next/issues/913
The back-to-top or manual scrolling would both trigger the 'scroll' event. 
So, we could directly modify the function "useActiveHeaderLinks".
We only need to check whether we are at the top of the page.
If we are at the top of the page, replace the 'hash' of the router with an empty string.
```javascript
// check if we have reached page top
const isAtPageTop = Math.abs(scrollTop - 0) < offset
// if we have reached page Top, replace current route hash with empty string
if (isAtPageTop) {
// replace current route hash with empty string
replaceWithoutScrollBehavior(router, {
hash: '',
force: true,
})
}
```
I think the 'isAtPageTop' checking is necessary.  If we use a reset strategy, i.e. replacing the …

Fix: issue-913 Remove header anchor when scrolling to page top

---

packages/@vuepress/theme-default/src/client/styles/normalize.scss
packages/@vuepress/theme-default/src/client/styles/page.scss

Currently, when users select the page content to copy & paste the text, it also selects the headings **#** anchors.
* Select the page content with your mouse or using keyboard (CRTL + A)
* Copy the text
* Paste it to an external document
You will see that all content headings (H1-H6) has a **#** prefix.
This PR removes the headings anchor-selection by defining the anchors as not selectable (`user-select: none;`).

feat(theme-default): headings anchor should not be selectable

---

tsconfig.json

Jest was removed in https://github.com/vuepress/vuepress-next/pull/1030

chore: remove jest types from typescript config

---

docs/zh/reference/default-theme/extending.md

I just edited the URL since the default theme has been moved to a new directory.

docs: Fix wrong url

---

packages/client/src/resolvers.ts

When the user does not configure the default title, expect to see `DOCS NAME` on the tab instead of `DOCS NAME |`.

feat(client):  modify the rendering of tab titles

---

packages/bundler-vite/src/build/renderPagePrefetchLinks.ts
packages/bundler-webpack/src/build/renderPagePrefetchLinks.ts

Adding `as` attribute for  `<link rel="prefetch" />`.
Reference -: https://web.dev/link-prefetch/#how-to-implement-rel=prefetch

Adding `as` attribute for  `<link rel="prefetch" />`  :)

---

ecosystem/plugin-shiki/package.json
ecosystem/plugin-shiki/src/node/shikiPlugin.ts
pnpm-lock.yaml

In my project, I use a custom theme for syntax highlighting. I can't update `shiki` version because it is not compatible with the old version

build: update shiki

---

ecosystem/theme-default/templates/build.html
packages/bundler-vite/src/build/renderPageStyles.ts
packages/bundler-webpack/src/build/renderPageStyles.ts
packages/client/templates/build.html

This is inspired from `Next.js`.
1) [Preload critical stylesheets to improve loading speed](https://web.dev/preload-critical-assets/).
2) Loading CSS top of other prefetches and preloads for faster CSS renders.
_Sorry if I made any mistakes :(_

Preloading critical style-sheets for improved performance 🚤  

---

ecosystem/theme-default/src/client/styles/_variables.scss
ecosystem/theme-default/src/client/styles/code.scss
packages/markdown/src/plugins/codePlugin/codePlugin.ts
packages/markdown/tests/plugins/__snapshots__/codePlugin.spec.ts.snap
packages/markdown/tests/plugins/__snapshots__/importCodePlugin.spec.ts.snap

This change make it possible to support ext marker automatically:

feat(markdown): make ext as attr instead of class

---

ecosystem/plugin-search/src/client/composables/useHotKeys.ts
ecosystem/plugin-search/src/client/utils/index.ts
ecosystem/plugin-search/src/client/utils/isFocusingTextControl.ts

Fixes an issue with the search plugin’s hotkey being triggered while typing into a text control (e.g. when setting the shortcut to <kbd>/</kbd> and then trying to type `/` into an `input[type=text]`).
This added logic is probably not entirely complete and accurate. It would probably be more accurate to only check `input` elements of certain types for example, but I think this should not cause issues.

fix(plugin-search): triggering hotkey while typing

---

ecosystem/plugin-container/src/node/containerPlugin.ts
packages/bundler-vite/src/build/build.ts
packages/bundler-vite/src/dev.ts
packages/bundler-webpack/src/build/build.ts
packages/bundler-webpack/src/dev/dev.ts
packages/cli/src/cli.ts
packages/cli/src/commands/dev/watchPageFiles.ts
packages/cli/src/commands/dev/watchUserConfigFile.ts
packages/cli/src/config/resolveAppConfig.ts
packages/cli/src/config/resolveUserConfigPath.ts
packages/core/src/app/appUse.ts
packages/core/src/pluginApi/createHookQueue.ts
packages/utils/package.json
packages/utils/src/index.ts
packages/utils/src/logger.ts
pnpm-lock.yaml

`picocolors` 14 times smaller and 2 times faster than `chalk`.
VitePress also use `picocolors`:
https://github.com/vuejs/vitepress/pull/659

feat(utils): migrate to picocolors

---

docs/guide/page.md
docs/zh/guide/page.md

> 文档docs/guide/page.md部分原文如下
假设这是你的 Markdown 文件所处的目录结构：
```sh
└─ docs
├─ guide
│  ├─ getting-started //根据下方路由路径表格，很显然，这里应该是page.md文件
│  └─ README.md
├─ contributing.md
└─ README.md
```
将 `docs` 目录作为你的 [sourceDir](../reference/cli.md) ，例如你在运行 `vuepress dev docs` 命令。此时，你的 Markdown 文件对应的路由路径为：
|      相对路径      |       路由路径        |
|--------------------|----------------------|
| `/README.md`       | `/`                  |
| `/index.md`        | `/`                  |
| `/contributing.md` | `/contributing.html` |
| `/guide/README.md` | `/guide/`            |
| `/guide/page.md`   | `/guide/page.html`   |

docs: fix the routing related errors of the page document in the guide

---

packages/bundler-vite/src/build/build.ts
packages/bundler-webpack/src/build/build.ts

Reverts vuepress/vuepress-next#1094
SSG result is not expected.
Lines like this absolutely will fail if this is done parrally.
https://github.com/vuepress/vuepress-next/blob/45c8e1cc3029bb68ab59ed5155b54bd774769231/packages/bundler-vite/src/build/renderPage.ts#L36-L37
https://vuepress.github.io SSG result is 404 page now.
cc @meteorlxy  @sanjaiyan-dev

Revert "perf: render pages in parallel"

---

docs/guide/migration.md

import default theme from package '@vuepress/theme-default' can cause an error: 
**Before**
Instead, I recommand import directly from 'vuepress', as is shown from the theme config.
```js
import { defaultTheme } from 'vuepress';
```
**After**

docs: use vuepress package in migration guide

---

docs/guide/assets.md
docs/zh/guide/assets.md
packages/markdown/src/plugins/assetsPlugin/assetsPlugin.ts
packages/markdown/src/plugins/assetsPlugin/resolveLink.ts
packages/markdown/tests/plugins/assetsPlugin.spec.ts

Recognize relative image links not staring with `./` in markdown.
BREAKING CHANGE: markdown image syntax does not support alias anymore, you should use `<img>` tag to use alias

feat(markdown): support relative image link without `./`

---

tsconfig.base.json

- Node16 targets ES2021
- https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax supported by typescript to force marking types, so we no longer need the eslint rule which is slower.

chore: update tsconfig

---

packages/client/src/resolvers.ts
packages/client/src/setupGlobalComputed.ts

Some pages were rendered with the wrong locale lang set. I have updated the resolver to look at the page data and the siteLocaleData. Additionally, I have set the default to be the same as the other Locale classes: `en-US`. This should ensure all pages have the correct locale lang set
fixes https://github.com/vuepress/vuepress-next/issues/1365

fix(client): fallback page lang to site lang (close #1365)

---

ecosystem/plugin-git/src/node/utils/getContributors.ts

A user might use multiple mechanisms of contributing code, some directly using their username and email, and others automated, typically with a "noreply" email address. Right now, this causes pages that use the "contributor" to have this somewhat awkward field:
This change treats the noreply addresses as the "same contributor", if one exists with the same name.
If a file has no such "noreply" addresses, or if there is no corresponding "normal" contributor, the field is unchanged.
Discussion: https://github.com/vuepress/vuepress-next/discussions/1336
**Before**
```
plugin-git % pnpm build && node -e 'import("./lib/node/utils/getContributors.js").then((mod)=>{mod.getContributors(["runatlantis.io/docs/README.md"], "/Users/lukemassa/atlantis").then((value)=>{console.log(value)})})'
> …
```

feat(plugin-git): remove duplicate no-reply contributors

---

packages/client/src/router.ts

Use sync afterEach to update route and pageData in a sync process.

fix(client): avoid mismatching between route path and page data (close #1249)

---

packages/core/src/page/resolvePagePermalink.ts
packages/core/tests/page/resolvePagePermalink.spec.ts
packages/shared/src/types/page.ts

Now users can set permalink: null to disable global `permalinkPattern` affect on certain pages.
This is more natural then setting permalink or permalinkPattern to page path in frontmatter.

feat(core): support permalink: null in frontmatter to disable permalink

---

e2e/docs/.vuepress/theme/client/config.ts
e2e/docs/.vuepress/theme/client/layouts/CssModulesLayout.vue
e2e/docs/.vuepress/theme/client/styles/styles.module.css
e2e/docs/.vuepress/theme/client/styles/variables.module.scss
e2e/docs/styles/css-modules.md
e2e/tests/styles/css-modules.spec.ts
packages/bundler-webpack/src/config/handleModuleStyles.ts

Closes #1557 
BREAKING CHANGE: For webpack bundler, css-modules will be enabled for `*.module.[ext]` files. The previous `*.[ext]?module` usage is no longer supported.

feat(bundler-webpack): enable css-modules for .module.css files (close #1557)

---

packages/cli/src/config/loadUserConfig.ts

This improves esbuild config:
1. bundle to correct node version to improve performance
2. add support for `import.meta.dirname` and `import.meta.filename` that is avaibable in node21+

feat(core): improve loading config file

---

packages/client/src/composables/clientData.ts
packages/client/src/composables/clientDataUtils.ts
packages/client/src/types/clientData.ts

Developers should prefer to use `useClientData` directly if they need multiple composables at one place:
```diff
- const frontmatter = usePageFrontmatter()
- const pageData = usePageData()
+ const { fontmatter, pageData } = useClientData()
```
This PR ensure frontmatter and pageData can be easily typed.

feat(client): improve client data types

---

packages/client/src/composables/clientDataUtils.ts
packages/client/src/setupGlobalComputed.ts
packages/client/src/types/clientData.ts
packages/client/src/types/index.ts

feat(client): provide client data aliases and utils

---

e2e/docs/router/navigate-by-link.md
e2e/docs/router/navigate-by-router.md
e2e/tests/router/navigate-by-link.spec.ts
e2e/tests/router/navigate-by-router.spec.ts
packages/markdown/src/plugins/linksPlugin/linksPlugin.ts

The default slugification function processes anchor links (hash fragments). If an anchor starts with a number (e.g., #123), it is replaced with `#_number` (e.g., `#_123`). This rule is designed to prevent potential URL conflicts, though manually written anchors like `#123` are rare in Markdown—hence the special handling.
Key Behaviors:
​Digits-Only Anchors:
`#123` → `#_123` (Adds _ to numeric anchors)
​Alphanumeric Anchors:
`#123a` → `#_123a` (Only the leading digits are modified)
​Non-Numeric Anchors:
`#section` → `#section` (No changes, letters remain untouched)
Why It Matters:
​URL Safety: Ensures numeric anchors (e.g., `#1`) don’t break routing in frameworks like Vue Router or static site generators.
​Markdown Context: Most anchors are auto-generated from headings (e.g., …

fix(markdown): avoid leading number in link hash

---

.vscode/settings.json
packages/core/src/app/resolveAppPages.ts
packages/utils/package.json
packages/utils/src/index.ts
pnpm-lock.yaml

refactor(utils): migrate from globby to tinyglobby
