- docs/.vuepress/config.ts
> chore: add navbar selectLanguageName

- docs/zh/guide/deployment.md
> docs: fix typo in zh translation

- packages/@vuepress/plugin-search/src/client/styles/search.css
- packages/@vuepress/theme-default/src/client/styles/home.scss
- packages/@vuepress/theme-default/src/client/styles/layout.scss
- packages/@vuepress/theme-default/src/client/styles/normalize.scss
- packages/@vuepress/theme-default/src/client/styles/page.scss
- packages/@vuepress/theme-default/src/client/styles/sidebar.scss
> feat(theme-default): enhance color transitions

- docs/advanced/cookbook/extending-a-theme.md
- docs/zh/advanced/cookbook/extending-a-theme.md
See ([a8de0a9](https://github.com/vuepress/vuepress-next/commit/a8de0a990711a2732f2f85b086e733fbd8a74110))
> docs(theme-default): add page slot of Layout.vue

- packages/@vuepress/theme-default/src/client/styles/navbar.scss
Variables should also be used here
> chore(theme-default): use css variables for toggle-sidebar-button

- packages/@vuepress/client/src/components/OutboundLink.ts
> fix(client): fix aria-hidden attribute of OutboundLink (close #427)

- packages/@vuepress/theme-default/src/client/components/PageNav.vue
- packages/@vuepress/theme-default/src/client/styles/page.scss
> feat(theme-default): make the arrows in page nav clickable

- docs/reference/default-theme/frontmatter.md
- docs/zh/reference/default-theme/frontmatter.md
- packages/@vuepress/theme-default/src/client/components/Home.vue
- packages/@vuepress/theme-default/src/shared/page.ts
> feat(theme-default): support heroImageDark frontmatter (close #526)

- packages/@vuepress/theme-default/src/client/styles/page.scss
> fix(theme-default): arrows not displaying in page nav

- docs/guide/deployment.md
> docs: add Layer0 to deployment guide

- packages/@vuepress/theme-default/src/client/components/Navbar.vue
- packages/@vuepress/theme-default/src/client/components/NavbarDropdown.vue
- packages/@vuepress/theme-default/src/client/components/NavbarItems.vue
- packages/@vuepress/theme-default/src/client/styles/navbar-dropdown.scss
Reverts vuepress/vuepress-next#736
> Revert "feat(theme-default): enhance header dropdown experience"

- docs/guide/deployment.md
- docs/zh/guide/deployment.md
> Update the docs

- docs/guide/getting-started.md
- docs/zh/guide/getting-started.md
- tsconfig.base.json
BREAKING CHANGES: node 12 is dropped
> build: drop support for node 12

- docs/reference/plugin/google-analytics.md
- docs/zh/reference/plugin/google-analytics.md
- ecosystem/plugin-google-analytics/src/client/composables/useGoogleAnalytics.ts
- ecosystem/plugin-google-analytics/src/client/config.ts
- ecosystem/plugin-google-analytics/src/node/googleAnalyticsPlugin.ts
- ecosystem/plugin-google-analytics/src/shared/index.ts
- ecosystem/plugin-google-analytics/src/shared/types.ts
Adds the ability to enable DebugView in development.
More information on DebugView: https://support.google.com/analytics/answer/7201382
> feat(plugin-google-analytics): add debug option

- packages/bundler-vite/package.json
- packages/bundler-vite/src/plugins/mainPlugin.ts
- pnpm-lock.yaml
Currently I cannot use dedicated PostCSS config file with VuePress.
Fix #1013
> fix(bundler-vite): fix loading postcss config

- packages/client/src/setupUpdateHead.ts
fixed #1174 https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2448#issue-1461331094
> fix(client): fix double quote in head tag

- docs/reference/default-theme/config.md
- docs/zh/reference/default-theme/config.md
- ecosystem/theme-default/src/client/styles/sidebar.scss
- ecosystem/theme-default/src/shared/nav.ts
> feat(theme-default): collapsible nested item in sidebar (close #883)

- packages/bundler-vite/src/build/build.ts
- packages/bundler-webpack/src/build/build.ts
Improving the performance by running the independent async functions in parallel ✈️.
Ref-: https://github.com/vuejs/vitepress/pull/1320
_Sorry if I made any mistakes :(_
> perf: render pages in parallel

- docs/reference/default-theme/styles.md
Just a small set of changes to make the text of this documentation page flow a bit more naturally.
> Add missing articles to the default-theme's styles docs

- docs/guide/deployment.md
- docs/zh/guide/deployment.md
Fixes the closed PR https://github.com/vuepress/vuepress-next/pull/1177. Because **Kinsta** doesn't have a free tier, the docs are just like the **Layer0**.
> docs: add Kinsta deployment guide link

- docs/reference/plugin/docsearch.md
- docs/zh/reference/plugin/docsearch.md
> add `appId` option in [docsearch's example](https://v2.vuepress.vuejs.org/reference/plugin/docsearch.html#locales)
> docs(plugin-docsearch): add appId in example code

- docs/guide/deployment.md
- docs/zh/guide/deployment.md
more about the merger: https://www.datacenterdynamics.com/en/news/limelight-acquires-yahoos-edgecast-cdn-service/
> docs: layer0 is now edgio

- ecosystem/plugin-docsearch/package.json
- ecosystem/plugin-docsearch/src/client/composables/useDocsearchHotkeyListener.ts
- pnpm-lock.yaml
> chore(plugin-docsearch): tweaks

- docs/guide/deployment.md
- docs/zh/guide/deployment.md
Based on the [latest CHANGELOG](https://github.com/vuepress/vuepress-next/blob/main/CHANGELOG.md#build-system), NodeJS version 14 support is dropped.
I've updated the `NODE_VERSION` environment variable for Netlify (in the [deployment page](https://vuejs.press/guide/deployment.html#netlify)) to be version 16.
**Before**
**After**
> docs: Update deployment.md

- package.json
This deps is no longer missing
> chore: update pnpm rules

- docs/zh/advanced/cookbook/usage-of-client-config.md
I found this line redundant, because 'path'  had already been imported in thie second line.
> docs: Update usage-client-config.md

- packages/client/src/routes.ts
- packages/core/src/app/prepare/preparePagesRoutes.ts
Page routes are taking too much size on large sites.
This is some production routes:
```
["/zh/tag/目录/", "/zh/tag/%E7%9B%AE%E5%BD%95/index.html"]], ["v-4268604a", "/zh/tag/%E9%A1%B5%E8%84%9A/", {
y: "p",
t: "页脚 标签",
I: 0
}, ["/zh/tag/页脚/", "/zh/tag/%E9%A1%B5%E8%84%9A/index.html"]], ["v-04c3401e", "/zh/tag/%E5%AF%BC%E8%88%AA%E6%A0%8F/", {
y: "p",
t: "导航栏 标签",
I: 0
}, ["/zh/tag/导航栏/", "/zh/tag/%E5%AF%BC%E8%88%AA%E6%A0%8F/index.html"]], ["v-27ec539c", "/zh/tag/%E4%BE%A7%E8%BE%B9%E6%A0%8F/", {
y: "p",
t: "侧边栏 标签",
I: 0
}, ["/zh/tag/侧边栏/", "/zh/tag/%E4%BE%A7%E8%BE%B9%E6%A0%8F/index.html"]], ["v-5458566b", "/zh/tag/%E5%AF%B9%E9%BD%90/", {
y: "p",
t: "对齐 标签",
I: 0
}, ["/zh/tag/对齐/", "/zh/tag/%E5%AF%B9%E9%BD%90/index.html"]], ["v-daa3d960", "/zh/tag/%E5%B1%9E%E6%80%A7/", {
y: "p",
t: "属性 标签",
I: …
```
> feat(core): reduce pageRoutes size

- packages/client/src/composables/pageData.ts
- packages/client/src/router.ts
- packages/client/src/setupGlobalComputed.ts
> fix(client): avoid mismatching between route path and page data (close #1249)

- packages/markdown/src/plugins/assetsPlugin/resolveLink.ts
- packages/markdown/tests/plugins/assetsPlugin.spec.ts
> fix(markdown): handle data uri correctly, close #1393

- docs/guide/migration.md
- docs/zh/guide/migration.md
Per Issue #1238 added some highlights for theme changes related to sidebars that we had to dig for in theme config.
N/A
> Add Sidebar changes to migration Docs

- packages/bundler-vite/src/plugins/vuepressMainPlugin.ts
> fix(bundler-vite): add vuepress to client packages list

- e2e/playwright.config.ts
Tried to enabled workers in build mode when running in CI
> test(e2e): enable workers in build mode of ci

- package.json
See https://github.com/pnpm/pnpm/releases/tag/v10.0.0
> build: allow building deps

- e2e/docs/.vuepress/client.ts
- e2e/docs/.vuepress/components/OnContentUpdated.vue
- e2e/docs/.vuepress/theme/client/layouts/Layout.vue
- packages/client/src/components/Content.ts
- packages/client/src/composables/onContentUpdated.ts
- packages/client/src/internal/contentUpdatedCallbacks.ts
Replace array with set to avoid duplicated callbacks
N/A
> refactor(client): use set to store content updated callbacks

- .github/workflows/check.yml
- .github/workflows/e2e.yml
- CONTRIBUTING.md
- CONTRIBUTING_zh.md
- packages/bundler-vite/package.json
- packages/bundler-webpack/tsup.config.ts
- packages/bundlerutils/package.json
- packages/cli/package.json
- packages/client/package.json
- packages/core/package.json
- packages/markdown/package.json
- packages/shared/package.json
- packages/utils/package.json
- packages/vuepress/package.json
- tsconfig.base.json
> build: drop node 18

- package.json
- packages/bundler-vite/package.json
- pnpm-lock.yaml
> feat(bundler-vite): upgrade vite to v7
